v0.15.0

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -331,7 +331,7 @@ jobs:
       matrix:
         include:
           - target: aarch64-apple-darwin
-          #- target: x86_64-apple-darwin
+          - target: x86_64-apple-darwin
     steps:
       - name: Checkout
         uses: actions/checkout@v6.0.1
@@ -341,19 +341,19 @@ jobs:
         with:
           disable_annotations: true
 
-      - name: Build FoundationDB Edition
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          rustup target add ${{matrix.target}}
-          # Get latest FoundationDB installer
-          curl --retry 5 -Lso foundationdb.pkg "$(gh api -X GET /repos/apple/foundationdb/releases --jq '.[] | select(.prerelease == false) | .assets[] | select(.name | test("${{startsWith(matrix.target, 'x86') && 'x86_64' || 'arm64'}}" + ".pkg$")) | .browser_download_url' | head -n1)"
-          echo "=== Package contents ==="
-          pkgutil --payload-files foundationdb.pkg || true
-          sudo installer -allowUntrusted -verbose -dumplog -pkg foundationdb.pkg -target /
-          cargo build --release --target ${{matrix.target}} -p stalwart --no-default-features --features "foundationdb s3 redis nats enterprise"
-          mkdir -p artifacts
-          mv ./target/${{matrix.target}}/release/stalwart ./artifacts/stalwart-foundationdb
+      #- name: Build FoundationDB Edition
+      #  env:
+      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #  run: |
+      #    rustup target add ${{matrix.target}}
+      #    # Get latest FoundationDB installer
+      #    curl --retry 5 -Lso foundationdb.pkg "$(gh api -X GET /repos/apple/foundationdb/releases --jq '.[] | select(.prerelease == false) | .assets[] | select(.name | test("${{startsWith(matrix.target, 'x86') && 'x86_64' || 'arm64'}}" + ".pkg$")) | .browser_download_url' | head -n1)"
+      #    echo "=== Package contents ==="
+      #    pkgutil --payload-files foundationdb.pkg || true
+      #    sudo installer -allowUntrusted -verbose -dumplog -pkg foundationdb.pkg -target /
+      #    cargo build --release --target ${{matrix.target}} -p stalwart --no-default-features --features "foundationdb s3 redis nats enterprise"
+      #    mkdir -p artifacts
+      #    mv ./target/${{matrix.target}}/release/stalwart ./artifacts/stalwart-foundationdb
 
       - name: Build
         run: |
